[colors]
cursor = { text = "#080808", cursor = "#9e9e9e" }

[colors.primary]
foreground = "#e4e4e4"
background = "#080808"

[colors.normal]
black = "#080808"
red = "#ff5d5d"
green = "#8cc85f"
yellow = "#e3c78a"
blue = "#80a0ff"
magenta = "#ff5195"
cyan = "#79dac8"
white = "#c6c6c6"
